ALTER TABLE tb_livros
    ADD COLUMN IF NOT EXISTS data_de_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_livros
    ADD COLUMN IF NOT EXISTS quantidade_de_uso INTEGER DEFAULT 0;