ALTER TABLE tb_user
    ADD COLUMN IF NOT EXISTS excluido BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS data_exclusao TIMESTAMP;

ALTER TABLE tb_usuario
    ADD COLUMN IF NOT EXISTS excluido BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS data_exclusao TIMESTAMP;
